version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_instance
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepass
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
